#pragma once

enum Error {
//	ERROR_PARSING,
	ERROR_PARSING_WRONGIDENTIFIER,
	ERROR_PARSING_WRONGFUNCTIONDEFINITION,
	ERROR_PARSING_WRONGFUNCTIONCLOSURE,
	ERROR_PARSING_HASTWOVARARG,
	ERROR_PARSING_WRONGCLASSDEFINITION,
	ERROR_PARSING_WRONGUSEDEFINITION,
//	ERROR_INTEGRATION,
	ERROR_INTEGRATION_WRONGDOT,
	ERROR_INTEGRATION_CANNOTFINDSYMBOL,
//	ERROR_RUNTIME,
	ERROR_RUNTIME_PARAMNEEDSVARIABLE,
};

void error(Error);
